"""Generate firmware/src/golden_vector.h from the decoded reference capture.

Takes one real row from the working NanoBerry <-> Raspberry Pi link, packs it exactly as
LPSPI + DMA would deliver it (MSB first, 32-bit words), and records the expected pixel
values. The firmware's SELFTEST command runs its unpack over this and compares, which
validates the decode path on the device without needing a camera attached.

    python tools/make_golden_vector.py --row 129

Requires tools/decode_golden.py to have been run once (it caches build/golden/bits.npy).
"""

import argparse
import os
import numpy as np

PP_BITS = 12
ROW_PP = 328
WIDTH = 320
TRAINING_PP = 8
ROW_BITS = ROW_PP * PP_BITS  # 3936
ROW_WORDS = ROW_BITS // 32   # 123


def find_row_starts(bits):
    alt = (bits[:-1] != bits[1:])
    d = np.diff(np.concatenate(([0], alt.view(np.int8), [0])))
    starts = np.where(d == 1)[0]
    ends = np.where(d == -1)[0]
    lens = ends - starts
    sel = lens >= 90
    return ends[sel] + 1, lens[sel]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bits", default="build/golden/bits.npy")
    ap.add_argument("--row", type=int, default=129,
                    help="row index within the first clean frame")
    ap.add_argument("--out", default="firmware/src/golden_vector.h")
    args = ap.parse_args()

    bits = np.load(args.bits)
    row_starts, run_lens = find_row_starts(bits)
    frame_first = np.where(run_lens > 1000)[0]
    # Frame 1 is the first frame with valid exposure (frame 0 is saturated).
    base = int(row_starts[frame_first[1] + args.row])

    # A row as the peripheral sees it starts at the 8 training words, which sit 96 bits
    # before the first pixel bit.
    start = base - TRAINING_PP * PP_BITS
    row = bits[start:start + ROW_BITS]
    assert len(row) == ROW_BITS, "capture too short for this row"

    words = []
    for w in range(ROW_WORDS):
        v = 0
        for b in range(32):
            v = (v << 1) | int(row[w * 32 + b])
        words.append(v)
    words.append(0)  # padding word so pp_at() may always read w[wi + 1]

    def pp_at(idx):
        bit = idx * PP_BITS
        wi, off = bit >> 5, bit & 31
        acc = (words[wi] << 32) | words[wi + 1]
        return (acc >> (52 - off)) & 0xFFF

    training = [pp_at(i) for i in range(TRAINING_PP)]
    assert all(t == 0x555 for t in training), f"unexpected training words: {training}"

    pixels = []
    for i in range(WIDTH):
        word = pp_at(TRAINING_PP + i)
        assert (word >> 11) == 1 and (word & 1) == 0, f"bad pixel word at {i}: {word:#05x}"
        pixels.append((word >> 1) & 0x3FF)

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", newline="\n") as f:
        f.write("// GENERATED by tools/make_golden_vector.py -- do not edit.\n")
        f.write("//\n")
        f.write("// One row captured from a working NanoBerry <-> Raspberry Pi SEIM link\n")
        f.write(f"// (doc/digital.csv, frame 1 row {args.row}), packed exactly as LPSPI + DMA\n")
        f.write("// deliver it: MSB first, 32-bit words. Used by the firmware SELFTEST.\n")
        f.write("#pragma once\n\n#include <stdint.h>\n\nnamespace golden {\n\n")
        f.write(f"constexpr uint32_t ROW_WORD_COUNT = {len(words)};\n")
        f.write("constexpr uint32_t ROW_WORDS_DATA[] = {\n")
        for i in range(0, len(words), 6):
            f.write("    " + " ".join(f"0x{w:08X}," for w in words[i:i + 6]) + "\n")
        f.write("};\n\n")
        f.write(f"constexpr uint32_t PIXEL_COUNT = {len(pixels)};\n")
        f.write("constexpr uint16_t EXPECTED_PIXELS[] = {\n")
        for i in range(0, len(pixels), 12):
            f.write("    " + " ".join(f"{p:4d}," for p in pixels[i:i + 12]) + "\n")
        f.write("};\n\n}  // namespace golden\n")

    print(f"wrote {args.out}")
    print(f"  row {args.row} of frame 1, {len(words)} words, {len(pixels)} pixels")
    print(f"  training words: {[hex(t) for t in training]}")
    print(f"  pixels: min={min(pixels)} max={max(pixels)} mean={sum(pixels)/len(pixels):.1f}")
    print(f"  first 8: {pixels[:8]}")


if __name__ == "__main__":
    main()
